spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:5432/sdl_lab1
    username: sdl
    password: sdl
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  port: 12345