server:
  port: 8099
spring:
  application:
    name: pppeis
  main:
    banner-mode: off

  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      host: localhost
      port: 27017
      database: pppeis

  neo4j:
    uri: 'bolt://localhost:7687'
    authentication:
      username: neo4j
      password: dev

  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 60000
      minimum-idle: 5
      idle-timeout: 20000
    url: 'jdbc:postgresql://localhost:5432/pppeis'
    username: pppeis
    password: pppeis
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQL95Dialect'
        default_schema: public
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

generation:
  study-plan: true
  students: true
  schedule: true
  attendance: true